export const BOOKING_MIN_LEAD_TIME_MINUTES = 120;
export const BOOKING_OPENING_HOUR = 8; // 08:00 EAT
export const BOOKING_CLOSING_HOUR = 21; // 21:00 EAT
export const BOOKING_SLOT_INTERVAL_MINUTES = 30;
export const BOOKING_LOOKAHEAD_DAYS = 30;
